version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalogo-sqlserver
    environment:
      SA_PASSWORD: "Catalogo404@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - catalogo-network

  catalogo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalogo-service
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ConnectionStrings__CatalogoConnection=Server=sqlserver;Database=CatalogoDB;User Id=sa;Password=Catalogo404@2025;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - catalogo-network

volumes:
  sqlserver_data:

networks:
  catalogo-network:
    driver: bridge

