apiVersion: v1
kind: Service
metadata:
  name: mongodb-catalogo-service
spec:
  selector:
    app: catalogo-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

